[domain.loc]
# Scheduler = * * * * * * 1 "%COMSPEC%" /c "osp project {host} & php artisan schedule:run"
# Queue = * * * * * * 1 "%COMSPEC%" /c "osp project {host} & php artisan queue:work --stop-when-empty"
